// <auto-generated />
namespace CreditCheck.Migrations
{
    using System;
    using CreditCheck.Data;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Metadata;

    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
               .HasAnnotation("ProductVersion", "3.0.0-servicing-35854")
               .HasAnnotation("Relational:MaxIdentifierLength", 128)
               .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CreditCheck.Models.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(15);

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(15);

                b.Property<DateTime>("DateOfBirth").IsRequired();

                b.Property<decimal>("Salary")
                    .IsRequired();

                b.Property<bool>("IsEligible")
                    .IsRequired();

                b.Property<DateTime>("CreatedOn");
                b.Property<string>("CreatedBy");
                b.Property<DateTime>("UpdatedOn");
                b.Property<string>("UpdatedBy");

                b.HasKey("Id");

                b.ToTable("Customer");
            });

            modelBuilder.Entity("CreditCheck.Models.Cards", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("CardType")
                   .IsRequired()
                   .HasMaxLength(15);

                b.Property<string>("BankName")
                  .IsRequired()
                  .HasMaxLength(100);

                b.Property<int>("AgeLimit")
                 .IsRequired();

                b.Property<decimal>("SalaryMin")
                 .IsRequired();

                b.Property<decimal>("APR")
                .IsRequired();

                b.Property<DateTime>("CreatedOn");
                b.Property<string>("CreatedBy");
                b.Property<DateTime>("UpdatedOn");
                b.Property<string>("UpdatedBy");

                b.HasKey("Id");

                b.ToTable("Cards");
            });
#pragma warning restore 612, 618
        }
    }
}
